/**
 * @name 地区枚举 
 */
import base from './base'
const {file_host} = base
export default [
    {
        icon:`${file_host}/1.png`,
        text:'每日健康提醒',
        url:'#/home'
    },
    {
        icon:`${file_host}/2.png`,
        text:'我的治病经验',
        url:'#/experience'
    },
    {
        icon:`${file_host}/3.png`,
        text:'疑难杂症120',
        url:'#/difficult'
    },
    {
        icon:`${file_host}/4.png`,
        text:'出生缺陷预防',
        url:'#/prevention'
    },
    {
        icon:`${file_host}/5.png`,
        text:'专家孕哺讲座',
        url:'#/lecture'
    },
    {
        icon:`${file_host}/6.png`,
        text:'青春婚恋须知',
        url:'#/notes'
    },
    {
        icon:`${file_host}/7.png`,
        text:'交友大世界',
        url:'#/firends'
    },
    {
        icon:`${file_host}/8.png`,
        text:'健康送爸妈',
        url:'#/health'
    },
    {
        icon:`${file_host}/9.png`,
        text:'百行孝居先'
    },
    {
        icon:'',
        text:''
    },
    {
        icon:`${file_host}/10.png`,
        text:'我是传播人'
    },
    {
        icon:'',
        text:''
    },
]