/**
 * @name 我是传播人目录 
 */
export default [
    {
        icon:'./icons/22.png',
        text:'我的传播朋友'
    },
    {
        icon:'./icons/33.png',
        text:'我的传播码'
    },
    {
        icon:'./icons/11.png',
        text:'我的账户'
    },
    {
        icon:'./icons/44.png',
        text:'我的孝敬卡'
    },
    {
        icon:'./icons/55.png',
        text:'我的头像'
    },
    {
        icon:'./icons/66.png',
        text:'我要传播'
    }
]